config/routes.rb
Rails.application.routes.draw do

  get 'blogs' => 'blog_post#index', as: 'blogs'
  get 'blogs/new' => 'blog_post#new', as: 'new_blog'
  post 'blogs' => 'blog_post#create'
  get 'blogs/:id' => 'blog_post#show', as:'blog'
  root 'blog_post#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_post_controller.rb
class BlogPostController < ApplicationController
    def index
        @blogs = BlogPost.all
    end
    def show
        @blog = BlogPost.find(params[:id])
    end
    def new
        # @blog = BlogPost.new
    end
    def create
        @blog = BlogPost.create(blog_params)
        if @blog.valid?
            redirect_to blogs_path
        else
            redirect_to new_blog_path
        end
    end
      
    private
    def blog_params
    params.require(:blog_post).permit(:title, :content)
    end
    
      

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_post_helper.rb
module BlogPostHelper
end

app/views/blog_post/index.html.erb
<h1> All Blogs </h1>
<% @blogs.each do |blog| %>
    <li>
    <%= link_to blog.title, blog_path(blog) %>
    </li>

    <% end %>
    <p><%= link_to 'New Post', new_blog_path %></p>

app/views/blog_post/new.html.erb
<h1>Create a New Blog Post</h1>
<%= form_with model: @blog_post do |form|  %>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <br>
    <%= form.label :content %>
    <%= form.text_field :content %>
    <br>
    <%= form.submit 'add post' %>
    <% end %>

    

app/views/blog_post/show.html.erb
<h1>Blog Post Details</h1>
<p>Post Name: <%= @blog.title %> </p>
<p>Content Name: <%= @blog.content %> </p>
<p><%= link_to 'All Blogs', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPostChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>